### ISSUE TITLE
Error in Installing Miniconda in RStudio

### ISSUE THREAD

**Issue by pjcalixto** [xytangtang/ProcData#3]
Good day!

I would like to request your help to solve my problem in installing miniconda in RStudio. I already installed Python 3.7 Miniconda3 Windows 64-bit.

In RStudio, it says:
Error in install_miniconda() : 
  cannot install Miniconda into a path containing spaces

Thank you in advance for helping my problem in installing.

![image](https://user-images.githubusercontent.com/68362862/87623046-119ff800-c757-11ea-83dd-7a2b1ebc9212.png)

**Comment by xytangtang** [comment]
What's the output of the following commands in RStudio?

`library(reticulate)`
`miniconda_path()`

**Comment by pjcalixto** [comment]
Hi,

The output is "C:/Users/Peter John Calixto/AppData/Local/r-miniconda".

However, I already remedy this issue. I created another user account were
no spaces in the path location. And it worked.

Thank you for your response.

*PETER JOHN R. CALIXTO*
Mobile: +63 928 454 6835; +63 926 778 6047
Email: pjcalixto.cem@gmail.com <peterjohn24calixto@gmail.com>
